export const ActionTypes = {
  GET_LIST_EMPLOYEE_REQUEST: "GET_LIST_EMPLOYEE_REQUEST",
  GET_LIST_EMPLOYEE_SUCCESS: "GET_LIST_EMPLOYEE_SUCCESS",

  GET_EMPLOYEE_DATA: " GET_EMPLOYEE_DATA",

  ADD_NEW_EMPLOYEE: "ADD_NEW_EMPLOYEE",
  ADD_NEW_EMPLOYEE_SUCCESS: "ADD_NEW_EMPLOYEE_SUCCESS",

  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_EMPLOYEE_SUCCESS: " DELETE_EMPLOYEE_SUCCESS",

  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_SUCCESS: " UPDATE_EMPLOYEE_SUCCESS",

  // lấy danh dách nhân viên
  GET_LIST_DATA_EMPLOYEE: " GET_LIST_DATA_EMPLOYEE",
  GET_LIST_DATA_EMPLOYEE_SUCCESS: " GET_LIST_DATA_EMPLOYEE_SUCCESS",

  GET_FORM_DATA: " GET_FORM_DATA",
  GET_FORM_DATA_SUCCESS: "GET_FORM_DATA_SUCCESS",

  //cạp nhật form
  UPDATE_FORM_EMPLOYEE: "UPDATE_FORM",
  UPDATE_FORM_EMPLOYEE_SUCCESS: " UPDATE_FORM_SUCCESS",

  // lanh dạo
  LEADER_ACTION: "LEADER_ACTION",

  // trinh lanh dao
  ADD_REGIST: "ADD_REGIST",
  ADD_REGIST_SUCCESS: "ADD_REGIST_SUCCESS",
};
